---
title: "visdat"
output: html_document
---

```{r setup, include=FALSE}
# change figure resolution
knitr::opts_chunk$set(dpi=300)

library(palmerpenguins)
library(visdat)
library(tidyverse)
```

### Visualize dataframe

```{r vis_dat}
visdat::vis_dat(penguins)
```

### Visualize missing data
```{r vis_miss}
visdat::vis_miss(penguins)

# cluster the missingness
visdat::vis_miss(penguins, cluster = TRUE)

# arrange the columns by most missingness
visdat::vis_miss(penguins, sort_miss = TRUE)
```

### Compare dataframes with <span style="color: red;">same dimension</span>.
```{r vis_compare}
# change penguins data for comparison
penguins_diff <- penguins %>%
  dplyr::mutate(year = 2007L)

# compare dataframes
visdat::vis_compare(penguins, penguins_diff)
```

### Visualize certain conditions
```{r vis_expect}
# check dataframe
visdat::vis_expect(penguins, ~.x >= 50)

# check variable
visdat::vis_expect(penguins["bill_length_mm"], ~.x >= 50)
```

### Visualize correlation
```{r vis_cor}
# create dataframe with numeric values
penguins_num <- penguins %>% 
  dplyr::select(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g)

visdat::vis_cor(penguins_num)
```

### Further reading
- naniar package for missing values: https://github.com/njtierney/naniar